import { sql } from "drizzle-orm";
import {
  boolean,
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  unique,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";

export const users = pgTable("users", {
  userId: text("user_id").primaryKey(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export const SUBSCRIPTION_PLANS = ["hobby", "pro"] as const;
export type SubscriptionPlan = (typeof SUBSCRIPTION_PLANS)[number];

export const SUBSCRIPTION_STATUSES = [
  "active",
  "trialing",
  "past_due",
  "canceled",
  "incomplete",
] as const;
export type SubscriptionStatus = (typeof SUBSCRIPTION_STATUSES)[number];

export const subscriptions = pgTable(
  "subscriptions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.userId, { onDelete: "cascade" }),
    plan: text("plan").notNull().default("hobby"),
    status: text("status").notNull().default("trialing"),
    trialEndsAt: timestamp("trial_ends_at", { withTimezone: true }),
    stripeCustomerId: text("stripe_customer_id"),
    stripeSubscriptionId: text("stripe_subscription_id"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index("subscriptions_user_id_idx").on(table.userId),
    unique("subscriptions_user_id_unique").on(table.userId),
    index("subscriptions_stripe_customer_id_idx").on(table.stripeCustomerId),
    unique("subscriptions_stripe_subscription_id_unique").on(
      table.stripeSubscriptionId,
    ),
  ],
);

export const apiTokens = pgTable(
  "api_tokens",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.userId, { onDelete: "cascade" }),
    name: text("name").notNull(),
    prefix: text("prefix").notNull(),
    hashedToken: text("hashed_token").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
    revokedAt: timestamp("revoked_at", { withTimezone: true }),
    // Nullable and opt-in at mint time (server/api/tokens/index.post.ts): a
    // NULL expiresAt means "never expires", preserving today's behavior for
    // every token minted before this column existed and for anyone who mints
    // a new token without requesting an expiry.
    expiresAt: timestamp("expires_at", { withTimezone: true }),
  },
  (table) => [
    index("api_tokens_user_id_idx").on(table.userId),
    unique("api_tokens_hashed_token_unique").on(table.hashedToken),
  ],
);

export const sources = pgTable(
  "sources",
  {
    uuid: uuid("uuid").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.userId, { onDelete: "cascade" }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    type: text("type").notNull(),
    name: text("name").notNull(),
    provider: text("provider"),
    // Provider signature-verification secret (see server/utils/signatureVerifier.ts).
    // GitHub and Stripe verify via HMAC, which needs the raw secret at verify
    // time, so those are stored in plaintext (Stripe's is user-supplied —
    // Stripe issues it — GitHub's is generated by us). Zapier/Shortcuts verify
    // by plain equality, so only a SHA-256 hash of the generated secret is
    // stored; the plaintext is revealed once, at creation, and never persisted.
    providerSecret: text("provider_secret"),
    endpointSlug: text("endpoint_slug").notNull(),
    routeFolder: text("route_folder").notNull(),
    fieldMapping: jsonb("field_mapping"),
    lastHitAt: timestamp("last_hit_at", { withTimezone: true }),
    recordCount: integer("record_count").default(0).notNull(),
    throttleWindowStart: timestamp("throttle_window_start", {
      withTimezone: true,
    })
      .defaultNow()
      .notNull(),
    throttleCount: integer("throttle_count").default(0).notNull(),
  },
  (table) => [
    index("sources_user_id_idx").on(table.userId),
    unique("sources_endpoint_slug_unique").on(table.endpointSlug),
  ],
);

export const RECORD_STATUSES = ["synced", "pending", "error"] as const;
export type RecordStatus = (typeof RECORD_STATUSES)[number];

export const records = pgTable(
  "records",
  {
    uuid: uuid("uuid").primaryKey().defaultRandom(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    userId: text("user_id")
      .notNull()
      .references(() => users.userId, { onDelete: "cascade" }),
    title: text("title").notNull(),
    content: text("content").notNull(),
    sourceId: uuid("source_id").references(() => sources.uuid, {
      onDelete: "set null",
    }),
    source: text("source"),
    status: text("status").notNull().default("pending"),
    filePath: text("file_path"),
    tags: jsonb("tags"),
    frontmatter: jsonb("frontmatter"),
    syncedAt: timestamp("synced_at", { withTimezone: true }),
    errorMessage: text("error_message"),
  },
  (table) => [
    // records_user_id_idx is a strict leading-column prefix of the composite
    // below, so the composite already serves every plain user_id lookup. It is
    // kept for now (dropping an index is out of scope for "add an index") and
    // flagged as a follow-up removal candidate, not left redundant by oversight.
    index("records_user_id_idx").on(table.userId),
    // Composite backing the two hottest record paths: the inbox list
    // (server/api/records/index.get.ts) filters by user_id and orders by
    // (created_at desc, uuid desc), and countRecordsCreatedThisMonth
    // (server/utils/recordUsage.ts) runs a user_id + created_at >= monthStart
    // COUNT on every webhook ingest. Without it both fall back to a sort/heap
    // scan as records grow. created_at and uuid are descending with NULLS FIRST
    // (Postgres' default for DESC, which is what the bare `desc()` ORDER BY
    // emits) so the planner can walk the index in the inbox's exact order and
    // skip the Sort node; a DESC NULLS LAST index would not match that pathkey.
    index("records_user_id_created_at_idx").on(
      table.userId,
      table.createdAt.desc().nullsFirst(),
      table.uuid.desc().nullsFirst(),
    ),
    index("records_status_idx").on(table.status),
    // Backs the ON DELETE SET NULL FK to sources.uuid: deleting a source
    // causes Postgres to null out every referencing records.source_id, which
    // without this index means a full table scan of records per source delete.
    index("records_source_id_idx").on(table.sourceId),
    // Trigram GIN indexes back the ILIKE `%term%` search in
    // server/api/records/index.get.ts so title/content search stays fast at
    // scale. Requires the pg_trgm extension (enabled in migration 0011).
    index("records_title_trgm_idx").using(
      "gin",
      table.title.op("gin_trgm_ops"),
    ),
    index("records_content_trgm_idx").using(
      "gin",
      table.content.op("gin_trgm_ops"),
    ),
    // One record per (user, case-insensitive file_path): closes the TOCTOU race
    // and the client-supplied-path duplicate window that the app-level suffix
    // (server/utils/filePathCollision.ts) cannot, so two records can never map
    // to the same synced file. Partial — a NULL or empty file_path means "no
    // file yet" and must not collide with another. Case-insensitive to mirror
    // resolveUniqueFilePath, which treats the CLI's case-insensitive
    // filesystems (macOS/Windows) as the source of truth. text_pattern_ops lets
    // this same index also back the left-anchored collision-prefix lookup
    // (lower(file_path) LIKE 'stem%') regardless of the database locale, so no
    // second index is needed. See migration 0022.
    uniqueIndex("records_user_id_file_path_lower_unique")
      .on(table.userId, sql`lower(${table.filePath}) text_pattern_ops`)
      .where(sql`${table.filePath} is not null and ${table.filePath} <> ''`),
  ],
);

export const EVENT_KINDS = ["ok", "dim", "warn", "err"] as const;
export type EventKind = (typeof EVENT_KINDS)[number];

export const events = pgTable(
  "events",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    userId: text("user_id")
      .notNull()
      .references(() => users.userId, { onDelete: "cascade" }),
    ts: timestamp("ts", { withTimezone: true }).defaultNow().notNull(),
    kind: text("kind").notNull(),
    message: text("message").notNull(),
    recordUuid: uuid("record_uuid"),
    sourceId: uuid("source_id").references(() => sources.uuid, {
      onDelete: "set null",
    }),
  },
  (table) => [
    index("events_user_id_ts_idx").on(table.userId, table.ts),
    // Same rationale as records_source_id_idx: backs the ON DELETE SET NULL FK
    // to sources.uuid so nulling events.source_id on a source delete does not
    // seq-scan events.
    index("events_source_id_idx").on(table.sourceId),
  ],
);

export const userSettings = pgTable("user_settings", {
  userId: text("user_id")
    .primaryKey()
    .references(() => users.userId, { onDelete: "cascade" }),
  vaultDir: text("vault_dir").notNull().default("~/Documents/Vault"),
  filenameTemplate: text("filename_template")
    .notNull()
    .default("{{date}}-{{slug}}.md"),
  autoSync: boolean("auto_sync").notNull().default(true),
  autoDelete: boolean("auto_delete").notNull().default(true),
  frontmatter: boolean("frontmatter").notNull().default(true),
  conflictStrategy: text("conflict_strategy").notNull().default("suffix"),
  theme: text("theme").notNull().default("system"),
  accentColor: text("accent_color").notNull().default("#a855f7"),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});
