import {
  createHash,
  createHmac,
  randomBytes,
  timingSafeEqual,
} from "node:crypto";
import {
  GITHUB_PROVIDER,
  MANUAL_SECRET_PROVIDER_IDS,
  ROTATABLE_PROVIDER_IDS,
  SECRET_BACKED_PROVIDER_IDS,
  SHARED_SECRET_HEADER,
  SHARED_SECRET_PROVIDER_IDS,
  STRIPE_PROVIDER,
} from "#shared/utils/webhookSecrets";

// Exported so every caller that needs to read/forward these headers (the hooks
// endpoint's buildProviderHeaders) imports the same constant instead of
// re-declaring it — a renamed header here must not be able to silently stop
// being forwarded there.
export const STRIPE_SIGNATURE_HEADER = "stripe-signature";
const STRIPE_TIMESTAMP_PREFIX = "t=";
const STRIPE_V1_PREFIX = "v1=";
const STRIPE_TIMESTAMP_TOLERANCE_SECONDS = 300;

// GitHub signs deliveries with a per-webhook secret the user pastes into their
// repo's webhook settings, so verification needs that source's own secret
// rather than a single global one.
export const GITHUB_SIGNATURE_HEADER = "x-hub-signature-256";
const GITHUB_SIGNATURE_PREFIX = "sha256=";

// 24 random bytes -> 48 hex chars, ~192 bits of entropy: comfortably beyond
// brute-force range for a value transmitted over HTTPS only.
const PROVIDER_SECRET_BYTE_LENGTH = 24;

// Re-exported from the shared module (the single source of provider ids) so
// existing importers of these from this file keep working while the HMAC
// dispatch below and the shared provider lists stay on the same literals.
export { GITHUB_PROVIDER, STRIPE_PROVIDER };

// Zapier and Apple Shortcuts share the same verification method (a static
// secret compared via the shared-secret header) since neither can compute an
// HMAC natively — GitHub is secret-backed too, but verified separately via
// real HMAC, so it is deliberately not in this list. Sourced from
// shared/utils/webhookSecrets.ts so the client (SourceCard.vue) can use the
// same list without pulling in this file's node:crypto import.
export const SHARED_SECRET_PROVIDERS = SHARED_SECRET_PROVIDER_IDS;

// Providers whose secret is generated by this app at source-creation time
// (as opposed to Stripe, whose secret is issued by Stripe itself and pasted
// in by the user — see MANUAL_SECRET_PROVIDERS). Sourced from
// shared/utils/webhookSecrets.ts (GitHub + the shared-secret providers) so the
// client rotate-secret UI reads the same list without this file's node:crypto.
export const SECRET_BACKED_PROVIDERS = SECRET_BACKED_PROVIDER_IDS;
export type SecretBackedProvider = (typeof SECRET_BACKED_PROVIDERS)[number];

// Stripe assigns the signing secret when the user creates their own Stripe
// webhook endpoint; we cannot generate it, so the user supplies it at
// source-creation time instead (see server/api/sources/index.post.ts).
export const MANUAL_SECRET_PROVIDERS = MANUAL_SECRET_PROVIDER_IDS;

// Every provider identity the backend knows how to verify at all — used to
// reject an unrecognized `provider` string at source-creation time rather
// than accepting it and permanently 401ing every delivery afterward. This is
// exactly the set with a rotatable secret, so it re-exports the shared list
// the rotate-secret UI gates on rather than re-composing the union here.
export const KNOWN_PROVIDERS = ROTATABLE_PROVIDER_IDS;

export function isSecretBackedProvider(
  provider: string,
): provider is SecretBackedProvider {
  return (SECRET_BACKED_PROVIDERS as readonly string[]).includes(provider);
}

export function isManualSecretProvider(
  provider: string,
): provider is (typeof MANUAL_SECRET_PROVIDERS)[number] {
  return (MANUAL_SECRET_PROVIDERS as readonly string[]).includes(provider);
}

// The verification-method predicate: routes to equality comparison via the
// shared-secret header (as opposed to HMAC). Today this happens to be the
// same set as isHashedStorageProvider below, but the two answer different
// questions — a future shared-secret provider stored in plaintext should
// still dispatch here without also being hashed, so keep them separate.
export function isSharedSecretProvider(
  provider: string,
): provider is (typeof SHARED_SECRET_PROVIDERS)[number] {
  return (SHARED_SECRET_PROVIDERS as readonly string[]).includes(provider);
}

// The storage-format predicate: shared-secret providers are compared by
// equality (never HMAC'd), so unlike GitHub/Stripe's HMAC secret they never
// need to be read back in plaintext — only a hash has to be stored. See
// hashSharedSecret below.
export function isHashedStorageProvider(
  provider: string,
): provider is (typeof SHARED_SECRET_PROVIDERS)[number] {
  return (SHARED_SECRET_PROVIDERS as readonly string[]).includes(provider);
}

export function isKnownProvider(provider: string): boolean {
  return (KNOWN_PROVIDERS as readonly string[]).includes(provider);
}

// The single normalization boundary for provider identity: creation-time
// derivation/validation and verification-time dispatch must agree on what
// "github" vs "GitHub " means, or a source can be created successfully and
// then never verify a single delivery.
export function normalizeProvider(provider: string | null | undefined): string {
  return provider?.toLowerCase().trim() ?? "";
}

export function generateProviderSecret(): string {
  return randomBytes(PROVIDER_SECRET_BYTE_LENGTH).toString("hex");
}

export type VerificationResult = { ok: true } | { ok: false; reason: string };

export type StripeSignatureParts = {
  timestamp: string;
  signatures: string[];
};

export function parseStripeSignatureHeader(
  header: string,
): StripeSignatureParts | null {
  const parts = header.split(",");
  let timestamp = "";
  const signatures: string[] = [];

  for (const part of parts) {
    const trimmed = part.trim();

    if (trimmed.startsWith(STRIPE_TIMESTAMP_PREFIX)) {
      timestamp = trimmed.slice(STRIPE_TIMESTAMP_PREFIX.length);
      continue;
    }

    if (trimmed.startsWith(STRIPE_V1_PREFIX)) {
      signatures.push(trimmed.slice(STRIPE_V1_PREFIX.length));
    }
  }

  if (!timestamp || signatures.length === 0) {
    return null;
  }

  return { timestamp, signatures };
}

function computeStripeSignature(
  timestamp: string,
  rawBody: string,
  secret: string,
): string {
  const signedPayload = `${timestamp}.${rawBody}`;
  return createHmac("sha256", secret)
    .update(signedPayload, "utf8")
    .digest("hex");
}

// Builds a real Stripe-Signature header value from a source's own stored
// secret, so a caller can round-trip a synthetic payload through
// verifyStripeSignature exactly as a live Stripe delivery would (see the
// source test-event endpoint, server/api/sources/[uuid]/test.post.ts). Shares
// computeStripeSignature with the verifier above so the two can never sign
// and verify with different HMAC logic. Defaults to "now" like a live
// delivery would, but takes an explicit timestamp so tests can pin it.
export function buildStripeSignatureHeader(
  rawBody: string,
  secret: string,
  timestampSeconds: number = Math.floor(Date.now() / 1000),
): string {
  const timestamp = String(timestampSeconds);
  const signature = computeStripeSignature(timestamp, rawBody, secret);
  return `${STRIPE_TIMESTAMP_PREFIX}${timestamp},${STRIPE_V1_PREFIX}${signature}`;
}

// Single source of the GitHub HMAC digest, shared by verifyGithubSignature
// (compares against an incoming header) and buildGithubSignatureHeader below
// (builds one from a source's own stored secret for the test-event endpoint)
// so signing and verifying can never drift onto different algorithms.
function computeGithubSignatureHex(rawBody: string, secret: string): string {
  return createHmac("sha256", secret).update(rawBody, "utf8").digest("hex");
}

export function buildGithubSignatureHeader(
  rawBody: string,
  secret: string,
): string {
  return `${GITHUB_SIGNATURE_PREFIX}${computeGithubSignatureHex(rawBody, secret)}`;
}

function isTimestampFresh(timestamp: string): boolean {
  if (!/^\d+$/.test(timestamp)) {
    return false;
  }

  const timestampSeconds = parseInt(timestamp, 10);

  if (Number.isNaN(timestampSeconds)) {
    return false;
  }

  const nowSeconds = Math.floor(Date.now() / 1000);
  return (
    Math.abs(nowSeconds - timestampSeconds) <=
    STRIPE_TIMESTAMP_TOLERANCE_SECONDS
  );
}

function signaturesMatch(expected: Buffer, candidate: string): boolean {
  const candidateBuffer = Buffer.from(candidate, "hex");
  // Buffer.from("hex") silently drops invalid chars producing a shorter buffer;
  // the length check below catches that mismatch.
  return (
    expected.length === candidateBuffer.length &&
    timingSafeEqual(expected, candidateBuffer)
  );
}

function compareSignatures(expected: string, candidates: string[]): boolean {
  const expectedBuffer = Buffer.from(expected, "hex");
  return candidates.some((candidate) =>
    signaturesMatch(expectedBuffer, candidate),
  );
}

export function verifyStripeSignature(
  signatureHeader: string,
  rawBody: string,
  secret: string,
): VerificationResult {
  const parsed = parseStripeSignatureHeader(signatureHeader);

  if (!parsed) {
    return { ok: false, reason: "Invalid Stripe-Signature header format" };
  }

  if (!isTimestampFresh(parsed.timestamp)) {
    return {
      ok: false,
      reason: "Stripe webhook timestamp is too old or invalid",
    };
  }

  const expected = computeStripeSignature(parsed.timestamp, rawBody, secret);

  if (!compareSignatures(expected, parsed.signatures)) {
    return { ok: false, reason: "Stripe webhook signature mismatch" };
  }

  return { ok: true };
}

export function verifyGithubSignature(
  signatureHeader: string,
  rawBody: string,
  secret: string,
): VerificationResult {
  if (!signatureHeader.startsWith(GITHUB_SIGNATURE_PREFIX)) {
    return { ok: false, reason: "Invalid X-Hub-Signature-256 header format" };
  }

  const candidate = signatureHeader.slice(GITHUB_SIGNATURE_PREFIX.length);
  const expected = computeGithubSignatureHex(rawBody, secret);

  if (!compareSignatures(expected, [candidate])) {
    return { ok: false, reason: "GitHub webhook signature mismatch" };
  }

  return { ok: true };
}

// Zapier/Shortcuts secrets are compared by equality only (never HMAC'd), so —
// unlike GitHub/Stripe, whose HMAC verification requires the raw secret to
// stay recoverable — only a hash needs to be persisted. See
// isHashedStorageProvider and server/api/sources/index.post.ts, which reveals
// the plaintext once (at creation) and stores only this hash.
export function hashSharedSecret(secret: string): string {
  return createHash("sha256").update(secret, "utf8").digest("hex");
}

export function verifySharedSecret(
  providedSecret: string | undefined,
  storedSecretHash: string,
): VerificationResult {
  if (!providedSecret) {
    return {
      ok: false,
      reason: `Missing ${SHARED_SECRET_HEADER} header`,
    };
  }

  const providedHashBuffer = Buffer.from(
    hashSharedSecret(providedSecret),
    "hex",
  );
  const storedHashBuffer = Buffer.from(storedSecretHash, "hex");
  // Both sides are fixed-width SHA-256 digests, so a length mismatch only
  // ever indicates corrupted storage, never anything about the caller's
  // input — checking it first is safe and avoids timingSafeEqual throwing.
  const matches =
    providedHashBuffer.length === storedHashBuffer.length &&
    timingSafeEqual(providedHashBuffer, storedHashBuffer);

  if (!matches) {
    return { ok: false, reason: "Webhook secret mismatch" };
  }

  return { ok: true };
}

export type ProviderSignatureInput = {
  provider: string | null;
  headers: Record<string, string | undefined>;
  rawBody: string;
  secret: string | null;
};

function verifyStripeProvider(
  input: ProviderSignatureInput,
): VerificationResult {
  if (!input.secret) {
    return { ok: false, reason: "Stripe webhook secret is not configured" };
  }

  const signatureHeader = input.headers[STRIPE_SIGNATURE_HEADER];

  if (!signatureHeader) {
    return { ok: false, reason: "Missing Stripe-Signature header" };
  }

  return verifyStripeSignature(signatureHeader, input.rawBody, input.secret);
}

function verifyGithubProvider(
  input: ProviderSignatureInput,
): VerificationResult {
  if (!input.secret) {
    return { ok: false, reason: "GitHub webhook secret is not configured" };
  }

  const signatureHeader = input.headers[GITHUB_SIGNATURE_HEADER];

  if (!signatureHeader) {
    return { ok: false, reason: "Missing X-Hub-Signature-256 header" };
  }

  return verifyGithubSignature(signatureHeader, input.rawBody, input.secret);
}

function verifySharedSecretProvider(
  input: ProviderSignatureInput,
): VerificationResult {
  if (!input.secret) {
    return {
      ok: false,
      reason: "Webhook secret is not configured for this source",
    };
  }

  return verifySharedSecret(input.headers[SHARED_SECRET_HEADER], input.secret);
}

export function verifyProviderSignature(
  input: ProviderSignatureInput,
): VerificationResult {
  const provider = normalizeProvider(input.provider);

  if (provider === "") {
    // No provider configured: slug-only authentication, no signature required.
    return { ok: true };
  }

  if (provider === STRIPE_PROVIDER) {
    return verifyStripeProvider(input);
  }

  if (provider === GITHUB_PROVIDER) {
    return verifyGithubProvider(input);
  }

  if (isSharedSecretProvider(provider)) {
    return verifySharedSecretProvider(input);
  }

  return {
    ok: false,
    reason: `Unsupported provider for signature verification: ${input.provider}`,
  };
}
